name: Sample Pipeline
on: [push]

jobs:
  build:
    runs-on: selfhosted-aws-linux
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - uses: kishaningithub/setup-python-amazon-linux@v1
      with:
        python-version: '3.10'
